Ios/dev/capturer and render
AgoraIO/FaceUnityLegacy pull request #34
Opened 2019-11-01 06:18 UTC by ShengQiangLiu

2019-11-11 00:20 UTC, plutoless commented on Agora-Video-With-FaceUnity-iOS/AgoraWithFaceunity/Controllers/RoomViewController.m
>      UIInterfaceOrientation orientation = [UIApplication sharedApplication].statusBarOrientation;
如果不需要了就整个删掉吧

2019-11-11 00:22 UTC, plutoless commented on Agora-Video-With-FaceUnity-iOS/AgoraWithFaceunity/Controllers/RoomViewController.m
> +    [self.agoraKit setVideoEncoderConfiguration:[[AgoraVideoEncoderConfiguration alloc]initWithSize:AgoraVideoDimension1280x720
分辨率为什么要改？改了后可能会有额外性能消耗

2019-11-11 00:24 UTC, plutoless commented on Agora-Video-With-FaceUnity-iOS/AgoraWithFaceunity/Controllers/RoomViewController.m
>  - (IBAction)changeCaptureFormat:(UISegmentedControl *)sender {
不用的就函数就去掉吧，或者注释掉，UI上的开关也要关掉

2019-11-11 00:25 UTC, plutoless commented on Agora-Video-With-FaceUnity-iOS/AgoraWithFaceunity/Faceunity/authpack.h
> +static char g_auth_package[]={-110,-85,86,-44,-25,59,21,105,5,18,-5,8,78,-99,116,-68,30,29,118,121,16,96,106,109,-80,-48,90,31,-33,126,-16,58,43,-24,-36,-81,-83,-50,-95,-84,33,-3,-121,95,-99,-108,-74
证书不要传到线上

2019-11-11 00:25 UTC, plutoless commented on Agora-Video-With-FaceUnity-iOS/AgoraWithFaceunity/KeyCenter.m
> +    return @"0279f083791444fc835764dfedd614ce";
appid不要传到线上

2019-11-11 00:29 UTC, plutoless requested changes
1. 开源仓库不允许上传fu_auth, appid等信息，上传前要替换回占位符
2. 注释有点缺，关键的地方要补一下注释
3. libyuv库太大了，有没有别的办法，尽量不要传上代码仓库

2019-11-18 03:53 UTC, guohai commented on Agora-Video-With-FaceUnity-iOS/AgoraWithFaceunity.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = io.agora.TestProject;
这些不要随便改

2019-11-18 05:34 UTC, guohai commented on Agora-Video-With-FaceUnity-iOS/AgoraWithFaceunity/KeyCenter.m
> +    return ;
Should not delete it

2019-12-06 11:40 UTC, closed without merging